window.REZERO_DLE_DATA = [
  {
    id: "subaru",
    name: "Subaru Natsuki",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 172,
    age: 18,
    affiliation: ["Emilia Kampı"],
    elements: ["Yin", "Su (Ruh)"],
    divineProtection: false,
    authority: true,
    firstArc: 1,
    portrait: "images/chars/subaru.webp"
  },
  {
    id: "emilia",
    name: "Emilia",
    gender: "Kız",
    race: "Yarı-Elf",
    heightCm: 164,
    age: "?",
    affiliation: "Emilia Kampı",
    elements: ["Ateş", "Su (Ruh)", "Rüzgar (Ruh)", "Toprak (Ruh)"],
    divineProtection: false,
    authority: false,
    firstArc: 1,
    portrait: "images/chars/emilia.webp"
  },
   {
    id: "puck",
    name: "Puck",
    gender: "Erkek",
    race: "Yapay Ruh",
    heightCm: 9,
    age: 421,
    affiliation: "Emilia Kampı",
    elements: ["Ateş", "Su", "Rüzgar", "Toprak", "Yin", "Yang"],
    divineProtection: false,
    authority: false,
    firstArc: 1,
    portrait: "images/chars/puck.webp"
  },
  {
    id: "roswaal",
    name: "Roswaal L. Mathers",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 186,
    age: 400,
    affiliation: "Emilia Kampı",
    elements: ["Ateş", "Su", "Rüzgar", "Toprak", "Yin", "Yang"],
    divineProtection: false,
    authority: false,
    firstArc: 2,
    portrait: "images/chars/roswaal.webp"
  },
  {
    id: "ram",
    name: "Ram",
    gender: "Kız",
    race: "Oni",
    heightCm: 154,
    age: 19,
    affiliation: "Emilia Kampı",
    elements: ["Rüzgar"],
    divineProtection: false,
    authority: false,
    firstArc: 2,
    portrait: "images/chars/ram.webp"
  },
  {
    id: "rem",
    name: "Rem",
    gender: "Kız",
    race: "Oni",
    heightCm: 154,
    age: 19,
    affiliation: "Emilia Kampı",
    elements: ["Su"],
    divineProtection: false,
    authority: false,
    firstArc: 2,
    portrait: "images/chars/rem.webp"
  },
  {
    id: "beatrice",
    name: "Beatrice",
    gender: "Kız",
    race: "Yapay Ruh",
    heightCm: 130,
    age: "400+",
    affiliation: "Emilia Kampı",
    elements: ["Yin", "Su", "Rüzgar"],
    divineProtection: false,
    authority: false,
    firstArc: 2,
    portrait: "images/chars/beatrice.webp"
  },
  {
    id: "otto",
    name: "Otto Suwen",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 177,
    age: 21,
    affiliation: "Emilia Kampı",
    elements: ["Toprak"],
    divineProtection: true,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/otto.webp"
  },
  {
    id: "frederica",
    name: "Frederica Baumann",
    gender: "Kız",
    race: "Yarı-İnsan",
    heightCm: 180,
    age: 22,
    affiliation: "Emilia Kampı",
    elements: ["Rüzgar"],
    divineProtection: false,
    authority: false,
    firstArc: 4,
    portrait: "images/chars/frederica.webp"
  },
  {
    id: "garfiel",
    name: "Garfiel Tinzel",
    gender: "Erkek",
    race: "Yarı-İnsan",
    heightCm: 160,
    age: 15,
    affiliation: "Emilia Kampı",
    elements: ["Su"],
    divineProtection: true,
    authority: false,
    firstArc: 4,
    portrait: "images/chars/garfiel.webp"
  },
  {
    id: "petra",
    name: "Petra Leyte",
    gender: "Kız",
    race: "İnsan",
    heightCm: 140,
    age: 13,
    affiliation: "Emilia Kampı",
    elements: ["Yang"],
    divineProtection: false,
    authority: false,
    firstArc: 2,
    portrait: "images/chars/petra.webp"
  },
  {
    id: "meili",
    name: "Meili Portroute",
    gender: "Kız",
    race: "İnsan",
    heightCm: 145,
    age: 14,
    affiliation: "Anne (Capella)",
    elements: ["Yang"],
    divineProtection: true,
    authority: false,
    firstArc: 2,
    portrait: "images/chars/meili.webp"
  },
  {
    id: "patrasche",
    name: "Patrasche",
    gender: "Kız",
    race: "Yer Ejderi",
    heightCm: "?",
    age: "?",
    affiliation: "Emilia Kampı",
    elements: ["Yok"],
    divineProtection: true,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/patrasche.webp"
  },
  {
    id: "felt",
    name: "Felt",
    gender: "Kız",
    race: "İnsan",
    heightCm: 150,
    age: 15,
    affiliation: "Felt Kampı",
    elements: ["Yok"],
    divineProtection: true,
    authority: false,
    firstArc: 1,
    portrait: "images/chars/felt.webp"
  },
  {
    id: "rom",
    name: "Rom",
    gender: "Erkek",
    race: "Dev",
    heightCm: 220,
    age: 130,
    affiliation: "Felt Kampı",
    elements: ["Yok"],
    divineProtection: false,
    authority: false,
    firstArc: 1,
    portrait: "images/chars/rom.webp"
  },
  {
    id: "reinhard",
    name: "Reinhard van Astrea",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 184,
    age: 20,
    affiliation: "Felt Kampı",
    elements: ["Yok"],
    divineProtection: true,
    authority: false,
    firstArc: 1,
    portrait: "images/chars/reinhard.webp"
  },
  {
    id: "elsa",
    name: "Elsa Granhiert",
    gender: "Kız",
    race: "İnsan",
    heightCm: 168,
    age: 23,
    affiliation: "Anne (Capella)",
    elements: ["Yok"],
    divineProtection: false,
    authority: false,
    firstArc: 1,
    portrait: "images/chars/elsa.webp"
  },
  {
    id: "crusch",
    name: "Crusch Karsten",
	gender: "Kız",
    race: "İnsan",
    heightCm: 168,
    age: 21,
    affiliation: "Crusch Kampı",
    elements: ["Rüzgar"],
    divineProtection: true,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/crusch.webp"
  },
  {
    id: "felix",
    name: "Felix Argyle",
    gender: "Erkek",
    race: "Yarı-İnsan",
    heightCm: 168,
    age: 20,
    affiliation: "Crusch Kampı",
    elements: ["Su"],
    divineProtection: true,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/felix.webp"
  },
  {
    id: "wilhelm",
    name: "Wilhelm van Astrea",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 178,
    age: 62,
    affiliation: "Crusch Kampı",
    elements: ["Yok"],
    divineProtection: false,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/wilhelm.webp"
  },  
  {
    id: "anastasia",
    name: "Anastasia Hoshin",
    gender: "Kız",
    race: "İnsan",
    heightCm: 168,
    age: 23,
    affiliation: "Anastasia Kampı",
    elements: ["Yang"],
    divineProtection: false,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/anastasia.webp"
  },
  {
    id: "julius",
    name: "Julius Juukulius",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 179,
    age: 22,
    affiliation: "Anastasia Kampı",
    elements: ["Ateş (Ruh)", "Su (Ruh)", "Rüzgar (Ruh)", "Toprak (Ruh)", "Yin (Ruh)", "Yang (Ruh)"],
    divineProtection: true,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/julius.webp"
  },
  {
    id: "ricardo",
    name: "Ricardo Welkin",
    gender: "Erkek",
    race: "Yarı-İnsan",
    heightCm: 206,
    age: 40,
    affiliation: "Anastasia Kampı",
    elements: ["Yok"],
    divineProtection: false,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/ricardo.webp"
  },
  {
    id: "mimi",
    name: "Mimi Pearlbaton",
    gender: "Kız",
    race: "Yarı-İnsan",
    heightCm: 135,
    age: 15,
    affiliation: "Anastasia Kampı",
    elements: ["Toprak", "Su"],
    divineProtection: true,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/mimi.webp"
  },
  {
    id: "hetaro",
    name: "Hetaro Pearlbaton",
    gender: "Erkek",
    race: "Yarı-İnsan",
    heightCm: 135,
    age: 15,
    affiliation: "Anastasia Kampı",
    elements: ["Su"],
    divineProtection: true,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/hetaro.webp"
  },
  {
    id: "tivey",
    name: "Tivey Pearlbaton",
    gender: "Erkek",
    race: "Yarı-İnsan",
    heightCm: 135,
    age: 15,
    affiliation: "Anastasia Kampı",
    elements: ["Ateş"],
    divineProtection: true,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/hetaro.webp"
  },
  {
    id: "priscilla",
    name: "Priscilla Barielle",
    gender: "Kız",
    race: "İnsan",
    heightCm: 164,
    age: 20,
    affiliation: "Priscilla Kampı",
    elements: ["Yang"],
    divineProtection: true,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/priscilla.webp"
  },
  {
    id: "aldebaran",
    name: "Aldebaran",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 172,
    age: 40,
    affiliation: "Priscilla Kampı",
    elements: ["Ateş", "Su", "Rüzgar", "Toprak", "Yin", "Yang"],
    divineProtection: false,
    authority: true,
    firstArc: 3,
    portrait: "images/chars/aldebaran.webp"
  },
  {
    id: "heinkel",
    name: "Heinkel Astrea",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 185,
    age: 39,
    affiliation: "Astrea Hanesi",
    elements: ["Yok"],
    divineProtection: false,
    authority: false,
    firstArc: 5,
    portrait: "images/chars/heinkel.webp"
  },  
  {
    id: "petelgeuse",
    name: "Petelgeuse Romanée-Conti",
    gender: "Erkek",
    race: "Ruh",
    heightCm: 180,
    age: 402,
    affiliation: "Cadı Tarikatı",
    elements: ["Toprak"],
    divineProtection: false,
    authority: true,
    firstArc: 3,
    portrait: "images/chars/petelgeuse.webp"
  },
  {
    id: "lye",
    name: "Lye Batenkaitos",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 150,
    age: "?",
    affiliation: "Cadı Tarikatı",
    elements: ["Ateş", "Su", "Rüzgar", "Toprak", "Yin", "Yang"],
    divineProtection: false,
    authority: true,
    firstArc: 3,
    portrait: "images/chars/lye.webp"
  },
  {
    id: "regulus",
    name: "Regulus Corneas",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 173,
    age: 120,
    affiliation: "Cadı Tarikatı",
    elements: ["Yok"],
    divineProtection: false,
    authority: true,
    firstArc: 3,
    portrait: "images/chars/regulus.webp"
  },
  {
    id: "sirius",
    name: "Sirius Romanée-Conti",
    gender: "Kız",
    race: "?",
    heightCm: 168,
    age: "?",
    affiliation: "Cadı Tarikatı",
    elements: ["Ateş"],
    divineProtection: false,
    authority: true,
    firstArc: 5,
    portrait: "images/chars/sirius.webp"
  },
  {
    id: "capella",
    name: "Capella Emerada Lugunica",
    gender: "Kız",
    race: "?",
    heightCm: 145,
    age: "?",
    affiliation: "Cadı Tarikatı",
    elements: ["Yok"],
    divineProtection: false,
    authority: true,
    firstArc: 5,
    portrait: "images/chars/capella.webp"
  },
  {
    id: "roy",
    name: "Roy Alphard",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 150,
    age: "?",
    affiliation: "Cadı Tarikatı",
    elements: ["Ateş", "Su", "Rüzgar", "Toprak", "Yin", "Yang"],
    divineProtection: false,
    authority: true,
    firstArc: 5,
    portrait: "images/chars/roy.webp"
  },
  {
    id: "rui",
    name: "Rui Arneb",
    gender: "Kız",
    race: "İnsan",
    heightCm: 140,
    age: "?",
    affiliation: "Cadı Tarikatı",
    elements: ["Ateş", "Su", "Rüzgar", "Toprak", "Yin", "Yang"],
    divineProtection: false,
    authority: true,
    firstArc: 5,
    portrait: "images/chars/rui.webp"
  },
  {
    id: "pandora",
    name: "Pandora",
    gender: "Kız",
    race: "?",
    heightCm: 155,
    age: "?",
    affiliation: "Cadı Tarikatı",
    elements: ["Yok"],
    divineProtection: false,
    authority: true,
    firstArc: 4,
    portrait: "images/chars/pandora.webp"
  },
  {
    id: "kurgan",
    name: "Kurgan",
    gender: "Erkek",
    race: "Yarı-İnsan",
    heightCm: 213,
    age: "?",
    affiliation: "Cadı Tarikatı",
    elements: ["Yok"],
    divineProtection: false,
    authority: false,
    firstArc: 5,
    portrait: "images/chars/kurgan.webp"
  },
  {
    id: "theresia",
    name: "Theresia van Astrea",
    gender: "Kız",
    race: "İnsan",
    heightCm: 162,
    age: 46,
    affiliation: "Cadı Tarikatı",
    elements: ["Yang"],
    divineProtection: true,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/theresia.webp"
  },
  {
    id: "echidna",
    name: "Echidna",
    gender: "Kız",
    race: "İnsan",
    heightCm: 164,
    age: "400+",
    affiliation: "Cadılar",
    elements: ["Ateş", "Su", "Rüzgar", "Toprak", "Yin", "Yang"],
    divineProtection: false,
    authority: true,
    firstArc: 4,
    portrait: "images/chars/echidna.webp"
  },    
  {
    id: "sekhmet",
    name: "Sekhmet",
    gender: "Kız",
    race: "Dev",
    heightCm: 170,
    age: "400+",
    affiliation: "Cadılar",
    elements: ["Yok"],
    divineProtection: false,
    authority: true,
    firstArc: 4,
    portrait: "images/chars/sekhmet.webp"
  },
  {
    id: "daphne",
    name: "Daphne",
    gender: "Kız",
    race: "İnsan",
    heightCm: 140,
    age: "400+",
    affiliation: "Cadılar",
    elements: ["Yok"],
    divineProtection: false,
    authority: true,
    firstArc: 4,
    portrait: "images/chars/daphne.webp"
  },
  {
    id: "minerva",
    name: "Minerva",
    gender: "Kız",
    race: "İnsan",
    heightCm: 155,
    age: "400+",
    affiliation: "Cadılar",
    elements: ["Yok"],
    divineProtection: false,
    authority: true,
    firstArc: 4,
    portrait: "images/chars/minerva.webp"
  },
  {
    id: "carmilla",
    name: "Carmilla",
    gender: "Kız",
    race: "İnsan",
    heightCm: 158,
    age: "400+",
    affiliation: "Cadılar",
    elements: ["Yok"],
    divineProtection: false,
    authority: true,
    firstArc: 4,
    portrait: "images/chars/carmilla.webp"
  },
  {
    id: "typhon",
    name: "Typhon",
    gender: "Kız",
    race: "İnsan",
    heightCm: 125,
    age: "400+",
    affiliation: "Cadılar",
    elements: ["Yok"],
    divineProtection: false,
    authority: true,
    firstArc: 4,
    portrait: "images/chars/typhon.webp"
  },
  {
    id: "satella",
    name: "Satella",
    gender: "Kız",
    race: "Yarı-Elf",
    heightCm: 164,
    age: "400+",
    affiliation: "Cadılar",
    elements: ["Yin"],
    divineProtection: false,
    authority: true,
    firstArc: 4,
    portrait: "images/chars/satella.webp"
  },
  {
    id: "hector",
    name: "Hector",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 185,
    age: "?",
    affiliation: "Cadılar",
    elements: ["Yok"],
    divineProtection: false,
    authority: true,
    firstArc: 4,
    portrait: "images/chars/hector.webp"
  },
  {
    id: "fortuna",
    name: "Fortuna",
    gender: "Kız",
    race: "Elf",
    heightCm: 168,
    age: "100+",
    affiliation: "Elior Ormanı",
    elements: ["Ateş"],
    divineProtection: false,
    authority: false,
    firstArc: 4,
    portrait: "images/chars/fortuna.webp"
  },
  {
    id: "russell",
    name: "Russell Fellow",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 180,
    age: 30,
    affiliation: "Ticaret Loncası",
    elements: ["Yok"],
    divineProtection: true,
    authority: false,
    firstArc: 3,
    portrait: "images/chars/russell.webp"
  },
  {
    id: "rachins",
    name: "Rachins Hoffman",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 175,
    age: 23,
    affiliation: "Felt Kampı",
    elements: ["Ateş"],
    divineProtection: false,
    authority: false,
    firstArc: 1,
    portrait: "images/chars/rachins.webp"
  },
  {
    id: "gaston",
    name: "Gaston",
    gender: "Erkek",
    race: "İnsan",
    heightCm: 185,
    age: 26,
    affiliation: "Felt Kampı",
    elements: ["Yok"],
    divineProtection: false,
    authority: false,
    firstArc: 1,
    portrait: "images/chars/gaston.webp"
  },
  {
    id: "schult",
    name: "Schult Barielle",
    gender: "Erkek",
    race: "İnsan",
    heightCm: "130",
    age: "12",
    affiliation: "Priscilla Kampı",
    elements: ["Yok"],
    divineProtection: false,
    authority: false,
    firstArc: 5,
    portrait: "images/chars/schult.webp"
  },   
  {
    id: "liliana",
    name: "Liliana Masquerade",
    gender: "Kız",
    race: "İnsan",
    heightCm: "150",
    age: "22",
    affiliation: "Priestella",
    elements: ["Yok"],
    divineProtection: true,
    authority: false,
    firstArc: 5,
    portrait: "images/chars/liliana.webp"
  },
  {
    id: "joshua",
    name: "Joshua Juukulius",
    gender: "Erkek",
    race: "İnsan",
    heightCm: "173",
    age: "17",
    affiliation: ["Anastasia Kampı"],
    elements: ["Su"],
    divineProtection: false,
    authority: false,
    firstArc: 5,
    portrait: "images/chars/joshua.webp"
  }, 
];